# Generated by Django 5.1.4 on 2025-01-11 10:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_useraddress_verificationotp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[django.core.validators.RegexValidator("^\\+?1?\\d{9,13}$")],
                verbose_name="Phone Number",
            ),
        ),
        migrations.AlterField(
            model_name="useraddress",
            name="phone_number",
            field=models.CharField(
                max_length=20,
                validators=[django.core.validators.RegexValidator("^\\+?1?\\d{9,13}$")],
                verbose_name="Phone Number",
            ),
        ),
        migrations.CreateModel(
            name="VerifictionOtp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.IntegerField(verbose_name="Otp code")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("register", "Register"),
                            ("reset_password", "Reset password"),
                        ],
                        max_length=60,
                        verbose_name="Verification Type",
                    ),
                ),
                ("expires_in", models.DateTimeField(verbose_name="Expires in")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_otp",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Verification Otp",
                "verbose_name_plural": "Verification Otps",
            },
        ),
        migrations.DeleteModel(
            name="VerificationOtp",
        ),
    ]
